// @flow

export const CREATE_GUIDE = "CREATE_GUIDE";
export const UPDATE_GUIDE = "UPDATE_GUIDE";
export const LOAD_GUIDES_SUCCESS = "LOAD_GUIDES_SUCCESS";

export const FETCH_NAVIGATION_REQUEST = "FETCH_NAVIGATION_REQUEST";
export const FETCH_NAVIGATION_FAILURE = "FETCH_NAVIGATION_FAILURE";
export const FETCH_NAVIGATION_SUCCESS = "FETCH_NAVIGATION_SUCCESS";

export const UPDATE_SUBLOCATION = "UPDATE_SUBLOCATION";
export const LOAD_SUBLOCATIONS_SUCCESS = "LOAD_SUBLOCATIONS_SUCCESS";

export const UPDATE_METRIC = "UPDATE_METRIC";

export const LOAD_FILE = "LOAD_FILE";
export const LOAD_FILE_SUCCESS = "LOAD_FILE_SUCCESS";
export const RELEASE_FILE = "RELEASE_FILE";
export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const UPDATE_AUDIO = "UPDATE_AUDIO_PROGRESS";
export const MOVE_AUDIO_SLIDER = "MOVE_AUDIO_SLIDER";
export const MOVE_AUDIO_SLIDER_COMPLETE = "MOVE_AUDIO_SLIDER_COMPLETE";

export const INTERNET_CHANGED = "INTERNET_CHANGED";

export const ERROR_HAPPENED = "ERROR_HAPPENED";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const CREATE_DOWNLOAD_TASK_SUCCESS = "CREATE_DOWNLOAD_TASK_SUCCESS";
export const CANCEL_DOWNLOAD_TASK_SUCCESS = "CANCEL_DOWNLOAD_TASK_SUCCESS";
export const RESUME_DOWNLOAD_TASK_SUCCESS = "RESUME_DOWNLOAD_TASK_SUCCESS";
export const CLEAR_CACHE_DOWNLOAD_TASK_SUCCESS =
  "CLEAR_CACHE_DOWNLOAD_TASK_SUCCESS";
export const DOWNLOAD_TASK_PROGRESSED = "DOWNLOAD_TASK_PROGRESSED";
export const DOWNLOAD_TASK_COMPLETED = "DOWNLOAD_TASK_COMPLETED";
export const DOWNLOAD_INFO_CLOSED = "DOWNLOAD_INFO_CLOSED";
export const UPDATE_DOWNLOAD_TASK_ = "UPDATE_DOWNLOAD_TASK";
export const SET_DOWNLOAD_DATA_VERSION = "SET_DOWNLOAD_DATA_VERSION";

export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";
export const TOGGLE_MENU = "TOGGLE_MENU";

export const GEOLOCATION_UPDATE_SUCCESS = "GEOLOCATION_UPDATE_SUCCESS";
