platform :ios, '9.0'

target 'GuideHbg' do
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'Firebase/Core'
  #pod 'RNShare', :path => '../node_modules/react-native-share'
end
