platform :ios, '8.0'

target 'GuideHbg' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
	
  pod 'Firebase/Core'
  # Pods for GuideHbg
end
