target 'GuideHbg' do
  #use_frameworks!
  platform :ios, '8.0'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge'
  ]
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Core'
end




